%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-fake-joint-launch
Version:        0.0.4
Release:        1%{?dist}
Summary:        ROS fake_joint_launch package

License:        Apache License 2.0
URL:            http://wiki.ros.org/fake_joint_launch
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-abb-irb2400-support
Requires:       ros-melodic-controller-manager
Requires:       ros-melodic-fake-joint-driver
Requires:       ros-melodic-pr2-description
Requires:       ros-melodic-robot-state-publisher
Requires:       ros-melodic-roslaunch
Requires:       ros-melodic-rostest
Requires:       ros-melodic-rviz
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-fake-joint-driver
BuildRequires:  ros-melodic-roslaunch
BuildRequires:  ros-melodic-rostest

%description
Collection of the launch files for fake_joint_driver.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Wed Dec 18 2019 Tokyo Opensource Robotics Kyokai (TORK) Developer Team <dev@opensource-robotics.tokyo.jp> - 0.0.4-1
- Autogenerated by Bloom

